# Generated by Django 4.0.3 on 2022-04-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='value',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='value_per_panel',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='value_to_receive',
        ),
        migrations.AddField(
            model_name='counter',
            name='soma',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='quantity',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
