# Generated by Django 4.0.3 on 2022-04-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0003_rename_soma_counter_value_to_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='total',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
