# Generated by Django 4.0.3 on 2022-04-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0004_counter_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='total',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='value_to_receive',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
