# Generated by Django 4.0.3 on 2022-04-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0005_alter_counter_total_alter_counter_value_to_receive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='total',
        ),
    ]
