# Generated by Django 4.0.3 on 2022-04-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0009_counter_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
    ]
