# Generated by Django 4.0.3 on 2022-04-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0011_rename_value_to_receive_counter_values_to_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='quantities',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
