# Generated by Django 4.0.3 on 2022-04-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0012_counter_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='total',
        ),
    ]
