# Generated by Django 4.0.3 on 2022-04-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0015_alter_counter_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='quantities',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
