# Generated by Django 4.0.3 on 2022-04-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0018_alter_counter_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='quantities',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=2),
        ),
    ]
