# Generated by Django 4.0.3 on 2022-04-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0019_alter_counter_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='total',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
