# Generated by Django 4.0.3 on 2022-05-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0023_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
