# Generated by Django 4.0.3 on 2022-05-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0025_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
