# Generated by Django 4.0.3 on 2022-05-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0028_rename_perfil_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='total_to_receive',
            field=models.FloatField(blank=True, default='0'),
        ),
    ]
