# Generated by Django 4.0.3 on 2022-05-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0029_alter_counter_total_to_receive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantities',
        ),
    ]
