# Generated by Django 4.0.4 on 2022-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0030_delete_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='quantities',
            field=models.IntegerField(default='0'),
        ),
    ]
